name: Services API CI

on:
  push:
    branches: [ "main" ]

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow runs
        run: echo "Workflow started successfully!"
